### ISSUE TITLE
better

### ISSUE THREAD

**Issue by jdkaplan** [choochootrain/choochoo-toolkit#2]
https://github.com/choochootrain/choochoo-toolkit/blob/a6f0692790cec770d8453387aa239c3cb5980d78/vim/vimrc#L38

highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd BufWinLeave * call clearmatches()

**Comment by choochootrain** [comment]
nah dis is fine mang
